### ISSUE TITLE
Linter cannot find modules in 'node_modules' despite successful Webpack compilation

### ISSUE THREAD

**Issue by JustinWebb** [TypeStrong/atom-typescript#735]
I'm working on an Ionic 2 project using Atom 1.2.2.  I installed *atom-typescript* a few hours ago... A simple line like `import {App, Platform, StatusBar} from 'ionic/ionic';` shows up as a linter error despite Webpack compiling and running TS files without error:

Error: ​​_Cannot find module 'ionic/ionic’ at line 1 col 40 in www/app/app.ts_​

Webpack uses a `modulesDirectories` property to list the application's import paths.  These paths start at the node_modules directory; the path to  _ionic/ionic_ appears here as well.  I don't see how to inform the linter where to find Ionic.

Let me know if I should provide additional information.

**Comment by basarat** [comment]
Can you try `tsc -p pathToTsconfig.json`. Please leave a comment if that succeed cause that means *we* have a bug :Rose:

That import statement will only work if `iconic` *ships with its definitions* which I don't think it does. Check DefinitelyTyped + tsd to get definitions :rose:

**Comment by JustinWebb** [comment]
The output:
_error TS5014: Failed to parse file 'tsconfig.json/tsconfig.json': Unexpected token u._

**Comment by basarat** [comment]
Sorry try `tsc -p pathToDirectoryContainingTsconfig`

**Comment by JustinWebb** [comment]
1st result: 
_error TS5023: Unknown compiler option 'allowNonTsExtensions'._

2nd result (after removing Ionic default property):
```
/app/app.ts(1,40): error TS2307: Cannot find module 'ionic/ionic'.
www/app/app.ts(2,9): error TS2395: Individual declarations in merged declaration 'TabsPage' must be all exported or all local.
www/app/app.ts(2,24): error TS2307: Cannot find module './tabs/tabs'.
www/app/app.ts(3,23): error TS2307: Cannot find module './common/data/data'.
www/app/app.ts(4,25): error TS2307: Cannot find module './common/services/db.service'.
www/app/app.ts(5,25): error TS2307: Cannot find module './common/data/pol.config'.
www/app/app.ts(14,14): error TS2395: Individual declarations in merged declaration 'TabsPage' must be all exported or all local.
www/app/app.ts(16,10): error TS2339: Property 'platform' does not exist on type 'TabsPage'.
www/app/app.ts(17,10): error TS2339: Property 'root' does not exist on type 'TabsPage'.
www/app/app.ts(19,10): error TS2339: Property 'platform' does not exist on type 'TabsPage'.
```
These are the same errors that appear in atom-typescript's pane.

**Comment by basarat** [comment]
> These are the same errors that appear in atom-typescript's pane.

Hence not an error here. Please look at getting `iconic` definitions. Check https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by JustinWebb** [comment]
I installed the Ionic definition but I continue to receive the error from 2nd result above.  My updated `tsd.json`:
```
{
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "installed": {
    "angularjs/angular.d.ts": {
      "commit": "16134c168d021351acb1673ee9659644fc58c424"
    },
    "jquery/jquery.d.ts": {
      "commit": "16134c168d021351acb1673ee9659644fc58c424"
    },
    "chai/chai.d.ts": {
      "commit": "16134c168d021351acb1673ee9659644fc58c424"
    },
    "assertion-error/assertion-error.d.ts": {
      "commit": "16134c168d021351acb1673ee9659644fc58c424"
    },
    "mocha/mocha.d.ts": {
      "commit": "16134c168d021351acb1673ee9659644fc58c424"
    },
    "sinon/sinon.d.ts": {
      "commit": "16134c168d021351acb1673ee9659644fc58c424"
    },
    "node/node.d.ts": {
      "commit": "16134c168d021351acb1673ee9659644fc58c424"
    },
    "ionic/ionic.d.ts": {
      "commit": "16134c168d021351acb1673ee9659644fc58c424"
    }
  }
}
```

**Comment by basarat** [comment]
And does `tsc` error as well? if not try `sync` : https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#atom-typescript-is-complaining-about-not-finding-files-or-other-weird-errors :rose:
